version: "3.9"
services:
  backend:
    image: node:20
    working_dir: /app/backend
    volumes: [ ".:/app" ]
    command: sh -c "npm --prefix /app/backend install && node server.js"
    environment:
      - PORT=4000
      - CORS_ORIGIN=http://localhost:5173
    ports: [ "4000:4000" ]

  frontend:
    image: node:20
    working_dir: /app/frontend
    volumes: [ ".:/app" ]
    command: sh -c "npm --prefix /app/frontend install && npx vite"
    environment:
      - VITE_OWNER_USERNAME=${VITE_OWNER_USERNAME}
    ports: [ "5173:5173" ]
