version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - PORT=4000
      - CORS_ORIGIN=http://localhost
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - OWNER_USERNAME=${OWNER_USERNAME}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
    ports:
      - "4000:4000"
    volumes:
      - ./backend/data:/app/backend/data

  web:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:80"
